replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/product.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "500m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
    - name: CosmosDb__Host
    - name: CosmosDb__Key
    - name: ProductImagesUrl
    - name: ProductDetailImagesUrl
    - name: ISSUER
    - name: SECURITYKEY
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 20
    periodSeconds: 30
    port: 80
  readiness:
    path: /readiness
    timeoutSeconds: 5
    initialDelaySeconds: 100
    periodSeconds: 60
    port: 80
