replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/mobileapigw.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: ApplicationInsights__InstrumentationKey
    - name: PopularProductsApiUrl
    - name: ProductsApiUrl
    - name: ProfileApiUrl
    - name: LoginApiUrl
    - name: CouponsApiUrl
    - name: ImageClassifierApiUrl
    - name: StockApiUrl
    - name: ISSUER
    - name: SECURITYKEY
    - name: UseB2C
    - name: B2CIssuer
    - name: Authority
    - name: RegisterUsers
    - name: RegistrationUsersEndpoint
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: gwPath
      value: mobilebff
    - name: UseMlNetClassifier
      value: "true"

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 20
    periodSeconds: 30
    port: 80
  readiness:
    path: /readiness
    timeoutSeconds: 5
    initialDelaySeconds: 100
    periodSeconds: 60
    port: 80
